### ISSUE TITLE
missing './build_linux_bridge.sh' referenced in tutorial

### ISSUE THREAD

**Issue by cythrauL** [nccgroup/asatools#3]
in asatools/tutorial.md, subsection 

https://github.com/nccgroup/asatools/blob/91b1e946f2eb8288cb956003614222a22d0895c4/tutorial.md#linux-network-setup

The document makes reference to a 'build_linux_bridge.sh', but this isn't provided anywhere in the repo.

A google for it only seems to reference this tutorial document.

**Comment by fidgetingbits** [comment]
Ya, we never released it originally. I guess you solved your problem since you closed the issue, but just in case you want it, I just added it to [asadbg](https://github.com/nccgroup/asadbg/blob/master/build_linux_bridge.sh)
